In [557]:
import numpy as np
import matplotlib.pyplot as plt
import math

##### Method of logistic regression provided in the class ussing Newton Method.

In [ ]:
def logRegF(XX, yy):
    NN, DD = np.shape(XX)
    xdata = np.concatenate((np.ones((NN,1)), XX), axis=1)
    ww = np.zeros((DD+1,1))
    for i in range(1000)    :
        mu = 1/(1+np.exp(-np.dot(xdata,ww)))    
        S = np.diag(np.multiply(mu,(1-mu))[:,0])
        aux = np.linalg.inv(np.dot(np.dot(xdata.T,S),xdata))
        aux = np.dot(np.dot(aux,xdata.T), yy-mu)
        ww = ww + aux
    return ww 

In [556]:
data_arr = np.loadtxt('heightWeightData.txt', delimiter=',')

### Exercise 1

### Exercise 1.a)

In [550]:
def logRegG(XX, yy, learning_rate, iterations):
    NN, DD = np.shape(XX)
    xdata = np.concatenate((np.ones((NN,1)), XX), axis=1)
    ww = np.zeros((DD+1,1))
    for i in range(iterations):
        mu = 1/(1+np.exp(-np.dot(xdata,ww)))  
        dw = (1/NN)*(np.dot((mu-yy).T, xdata))
        deltaww = - (np.array([learning_rate]).T  * dw.T)
        ww = ww + deltaww
    return(ww)

### Exercise 1.b)

Iterations 500000

learning_rate = [0.1, 0.0001, 0.0001] 

In [551]:
XX = data_arr[:,1:]
yy = (data_arr[:,0] - 1).reshape((-1,1)).astype(int)
logRegG(XX,yy, [0.1, 0.0001, 0.0001], 500000)

array([[38.43451566],
       [-0.17318229],
       [-0.11493934]])

In [552]:
logRegF(XX,yy)

array([[38.50048852],
       [-0.17356863],
       [-0.11491363]])

I couldn't converge with the same learning rate for all the $\omega$. Even with that it take many iteration to converge.

### Exercise 1.c)

Iterations 3000

learning_rate = 0.1 

In [554]:
XX = data_arr[:,1:] - np.mean(data_arr[:,1:], axis=0)
yy = (data_arr[:,0] - 1).reshape((-1,1)).astype(int)
logRegG(XX,yy, 0.1, 3000)

array([[ 1.21070581],
       [-0.17356863],
       [-0.11491363]])

In [507]:
logRegF(XX,yy)

array([[ 1.21070582],
       [-0.17356863],
       [-0.11491363]])

### Exercise 1.d)

Iterations 500

learning_rate = 2 

In [555]:
XX = (data_arr[:,1:]- np.mean(data_arr[:,1:], axis=0)) / np.std(data_arr[:,1:], axis=0)
yy = (data_arr[:,0] - 1).reshape((-1,1)).astype(int)
logRegG(XX,yy, 2, 500)

array([[ 1.21070582],
       [-1.96089546],
       [-1.70013191]])

In [541]:
logRegF(XX,yy)

array([[ 1.21070582],
       [-1.96089547],
       [-1.7001319 ]])

### Exercise 2

In [562]:
px0_y0 = math.exp(2*math.cos(-1))/(2*math.pi*2.2796)
px0_y1 = math.exp(3*math.cos(0.9))/(2*math.pi*4.8808)

In [564]:
px0_y0

0.20571317317650958

In [563]:
px0_y1

0.21048175536784317

### Exercise 1.b)

In [621]:
x = -math.acos(math.log(4.8808)-math.log(2.2796))+1 + 2*math.pi

In [615]:
x = 0.5

In [616]:
math.exp(2*math.cos(x-1))/(2*math.pi*2.2796)

0.40384992952273907

In [617]:
math.exp(3*math.cos(x-1))/(2*math.pi*4.8808)

0.45364581817049004

In [607]:
math.pi

3.141592653589793

In [622]:
x

6.577718792924346

x>1.705