In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

from IPython.display import display, Markdown

##### Method of logistic regression provided in the class ussing Newton Method.

In [2]:
def logRegF(XX, yy):
    NN, DD = np.shape(XX)
    xdata = np.concatenate((np.ones((NN,1)), XX), axis=1)
    ww = np.zeros((DD+1,1))
    for i in range(1000)    :
        mu = 1/(1+np.exp(-np.dot(xdata,ww)))    
        S = np.diag(np.multiply(mu,(1-mu))[:,0])
        aux = np.linalg.inv(np.dot(np.dot(xdata.T,S),xdata))
        aux = np.dot(np.dot(aux,xdata.T), yy-mu)
        ww = ww + aux
    return ww 

### Exercise 1

In [3]:
data_arr = np.loadtxt('heightWeightData.txt', delimiter=',') #import the data

### Exercise 1.a)

To symplify the search of a suitable learning rate and number of iterations, those inputs were added to the function logRegR.  

In [4]:
def logRegG(XX, yy, learning_rate, iterations):
    NN, DD = np.shape(XX)
    xdata = np.concatenate((np.ones((NN,1)), XX), axis=1)
    ww = np.zeros((DD+1,1))
    for i in range(iterations):
        mu = 1/(1+np.exp(-np.dot(xdata,ww)))  
        dw = (1/NN)*(np.dot((mu-yy).T, xdata))
        deltaww = - (np.array([learning_rate]).T  * dw.T)
        ww = ww + deltaww
    return(ww)

### Exercise 1.b)

Iterations = 500000

learning_rate = [0.1, 0.0001, 0.0001] 

In [5]:
XX = data_arr[:,1:]
yy = (data_arr[:,0] - 1).reshape((-1,1)).astype(int)
print(logRegG(XX,yy, [0.1, 0.0001, 0.0001], 500000))

[[38.43451566]
 [-0.17318229]
 [-0.11493934]]


In [6]:
print(logRegF(XX,yy))

[[38.50048852]
 [-0.17356863]
 [-0.11491363]]


It wasn't converging with the same learning rate for all the $\omega$. Even with different rates it take many iteration to converge.

### Exercise 1.c)

Iterations = 3000

learning_rate = 0.1 

In [7]:
XX = data_arr[:,1:] - np.mean(data_arr[:,1:], axis=0)
yy = (data_arr[:,0] - 1).reshape((-1,1)).astype(int)
print(logRegG(XX,yy, 0.1, 3000))

[[ 1.21070581]
 [-0.17356863]
 [-0.11491363]]


In [8]:
print(logRegF(XX,yy))

[[ 1.21070582]
 [-0.17356863]
 [-0.11491363]]


### Exercise 1.d)

Iterations = 500

learning_rate = 2 

In [9]:
XX = (data_arr[:,1:]- np.mean(data_arr[:,1:], axis=0)) / np.std(data_arr[:,1:], axis=0)
yy = (data_arr[:,0] - 1).reshape((-1,1)).astype(int)
print(logRegG(XX,yy, 2, 500))

[[ 1.21070582]
 [-1.96089546]
 [-1.70013191]]


In [10]:
print(logRegF(XX,yy))

[[ 1.21070582]
 [-1.96089547]
 [-1.7001319 ]]


### Exercise 2

### Exercise 1.a)

It was used the python libraries to perform the calculatoin of $P(x=0|y_0)$ and $P(x=0|y_1)$

In [11]:
px0_y0 = math.exp(2*math.cos(-1))/(2*math.pi*2.2796)
px0_y1 = math.exp(3*math.cos(0.9))/(2*math.pi*4.8808)
display(Markdown(rf"""$P(x=0|y_0)={px0_y0}$

$P(x=0|y_1)={px0_y1}$"""))

$P(x=0|y_0)=0.20571317317650958$

$P(x=0|y_1)=0.21048175536784317$

As it can be seen, $P(x=0|y_0) < P(x=0|y_1)$ so the decision for $x=0$ is the class $y_1$.

### Exercise 1.b)

For the prediction be equal to $y_0$, the following inequality must be respeted.

$$P(x|y_0) > P(x|y_1)$$

To simplify let's assume the equality.

$$\frac{e^{2cos(x-1)}}{2\pi2.2796}=\frac{e^{3cos(x-1)}}{2\pi4.8808}$$
$$\Leftrightarrow 2cos(x-1) - ln(2.2796) = 3cos(x-1) - ln(4.8808)$$
$$\Leftrightarrow cos(x-1) = ln(\frac{4.8808}{2.2796})
\Leftrightarrow x = \pm cos^{-1}(ln\frac{4.8808}{2.2796})) + 1 + 2\pi n$$

Now regarding the inequality:  

$$cos^{-1}(ln(\frac{4.8808}{2.2796})) + 1 + 2\pi n < x < -cos^{-1}(ln(\frac{4.8808}{2.2796})) + 1 + 2\pi (n+1)$$
$$n \in \mathbb{N}$$

In [12]:
x_max = -math.acos(math.log(4.8808)-math.log(2.2796))+1 + 2*math.pi
x_min = math.acos(math.log(4.8808)-math.log(2.2796))+1

display(Markdown(rf"""$${x_min} +2\pi n< x < {x_max}+2\pi n$$"""))

$$1.70546651425524 +2\pi n< x < 6.577718792924346+2\pi n$$

### Exercise 1.c)

$$P(y_0|x) = \frac{P(x|y_0)P(y_0)}{P(x|y_0)P(y_0)+P(x|y_1)P(y_1)}$$

This results in:
$$P(y_0|x) = \frac{1}{1+\frac{P(x|y_1)P(y_1)}{P(x|y_0)P(y_0)}}$$

Since $P(y_0)=P(y_1)$:
$$P(y_0|x) = \frac{1}{1+exp(ln\frac{P(x|y_1)}{P(x|y_0)})}$$

$$ln\frac{\frac{e^{k_1cos(x-\mu_1)}}{2\pi I(k_1)}}{\frac{e^{k_0cos(x-\mu_0)}}{2\pi I(k_0)}} = 
ln\frac{I(k_0)e^{k_1cos(x-\mu_1)}}{I(k_1)e^{k_0cos(x-\mu_0)}} = 
ln\frac{I(k_0)}{I(k_1)} + k_1cos(x-\mu_1) - k_0cos(x-\mu_0)$$

Expanding, $k_1cos(x-\mu_1) - k_0cos(x-\mu_0)$:
$$\omega_1(cos(x)sen(-\theta)+sen(x)cos(-\theta)) =$$ 
$$ \omega_1(sen(x)cos(\theta)-cos(x)sen(\theta)) =$$ 
$$\omega_1sen(x-\theta)$$
where:
$$cos(-\theta) = \frac{k_1sen(\mu_1)-k_0sen(\mu_0)}{\sqrt{k_1^2-2k_1k_2cos(\mu_1+\mu_0)+k_0^2}}$$
$$sen(-\theta) = \frac{k_1cos(\mu_1)-k_0cos(\mu_0)}{\sqrt{k_1^2-2k_1k_2cos(\mu_1+\mu_0)+k_0^2}}$$
$$\omega_1 = \sqrt{k_1^2-2k_1k_2cos(\mu_1+\mu_0)+k_0^2}$$
$$\omega_0 = ln\frac{I(k_0)}{I(k_1)}$$

Replacing in $P(y_0|x)$, we have:
$$P(y_0|x) = \frac{1}{1+e^{\omega_0+\omega_1sen(x-\theta)}}$$